// WARNING: This file has automatically been generated on Tue, 08 Feb 2022 02:27:11 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nl80211

const (
	// GenlName as defined in nl80211/nl80211.h:45
	GenlName = "nl80211"
	// MulticastGroupConfig as defined in nl80211/nl80211.h:47
	MulticastGroupConfig = "config"
	// MulticastGroupScan as defined in nl80211/nl80211.h:48
	MulticastGroupScan = "scan"
	// MulticastGroupReg as defined in nl80211/nl80211.h:49
	MulticastGroupReg = "regulatory"
	// MulticastGroupMlme as defined in nl80211/nl80211.h:50
	MulticastGroupMlme = "mlme"
	// MulticastGroupVendor as defined in nl80211/nl80211.h:51
	MulticastGroupVendor = "vendor"
	// MulticastGroupNan as defined in nl80211/nl80211.h:52
	MulticastGroupNan = "nan"
	// MulticastGroupTestmode as defined in nl80211/nl80211.h:53
	MulticastGroupTestmode = "testmode"
	// EdmgBwConfigMin as defined in nl80211/nl80211.h:55
	EdmgBwConfigMin = 4
	// EdmgBwConfigMax as defined in nl80211/nl80211.h:56
	EdmgBwConfigMax = 15
	// EdmgChannelsMin as defined in nl80211/nl80211.h:57
	EdmgChannelsMin = 1
	// EdmgChannelsMax as defined in nl80211/nl80211.h:58
	EdmgChannelsMax = 0x3c
	// CmdGetMeshParams as defined in nl80211/nl80211.h:1443
	CmdGetMeshParams = CmdGetMeshConfig
	// CmdSetMeshParams as defined in nl80211/nl80211.h:1444
	CmdSetMeshParams = CmdSetMeshConfig
	// MeshSetupVendorPathSelIe as defined in nl80211/nl80211.h:1445
	MeshSetupVendorPathSelIe = MeshSetupIe
	// AttrScanGeneration as defined in nl80211/nl80211.h:3068
	AttrScanGeneration = AttrGeneration
	// AttrMeshParams as defined in nl80211/nl80211.h:3069
	AttrMeshParams = AttrMeshConfig
	// AttrIfaceSocketOwner as defined in nl80211/nl80211.h:3070
	AttrIfaceSocketOwner = AttrSocketOwner
	// AttrSaeData as defined in nl80211/nl80211.h:3071
	AttrSaeData = AttrAuthData
	// AttrCsaCOffBeacon as defined in nl80211/nl80211.h:3072
	AttrCsaCOffBeacon = AttrCntdwnOffsBeacon
	// AttrCsaCOffPresp as defined in nl80211/nl80211.h:3073
	AttrCsaCOffPresp = AttrCntdwnOffsPresp
	// WiphyNameMaxlen as defined in nl80211/nl80211.h:3101
	WiphyNameMaxlen = 64
	// MaxSuppRates as defined in nl80211/nl80211.h:3103
	MaxSuppRates = 32
	// MaxSuppHtRates as defined in nl80211/nl80211.h:3104
	MaxSuppHtRates = 77
	// MaxSuppRegRules as defined in nl80211/nl80211.h:3105
	MaxSuppRegRules = 128
	// TkipDataOffsetEncrKey as defined in nl80211/nl80211.h:3106
	TkipDataOffsetEncrKey = 0
	// TkipDataOffsetTxMicKey as defined in nl80211/nl80211.h:3107
	TkipDataOffsetTxMicKey = 16
	// TkipDataOffsetRxMicKey as defined in nl80211/nl80211.h:3108
	TkipDataOffsetRxMicKey = 24
	// HtCapabilityLen as defined in nl80211/nl80211.h:3109
	HtCapabilityLen = 26
	// VhtCapabilityLen as defined in nl80211/nl80211.h:3110
	VhtCapabilityLen = 12
	// HeMinCapabilityLen as defined in nl80211/nl80211.h:3111
	HeMinCapabilityLen = 16
	// HeMaxCapabilityLen as defined in nl80211/nl80211.h:3112
	HeMaxCapabilityLen = 54
	// MaxNrCipherSuites as defined in nl80211/nl80211.h:3113
	MaxNrCipherSuites = 5
	// MaxNrAkmSuites as defined in nl80211/nl80211.h:3114
	MaxNrAkmSuites = 2
	// MinRemainOnChannelTime as defined in nl80211/nl80211.h:3116
	MinRemainOnChannelTime = 10
	// ScanRssiTholdOff as defined in nl80211/nl80211.h:3119
	ScanRssiTholdOff = -300
	// CqmTxeMaxIntvl as defined in nl80211/nl80211.h:3121
	CqmTxeMaxIntvl = 1800
	// StaFlagMaxOldApi as defined in nl80211/nl80211.h:3225
	StaFlagMaxOldApi = StaFlagTdlsPeer
	// StaInfoDataAckSignalAvg as defined in nl80211/nl80211.h:3514
	StaInfoDataAckSignalAvg = StaInfoAckSignalAvg
	// FrequencyAttrPassiveScan as defined in nl80211/nl80211.h:3858
	FrequencyAttrPassiveScan = FrequencyAttrNoIr
	// FrequencyAttrNoIbss as defined in nl80211/nl80211.h:3859
	FrequencyAttrNoIbss = FrequencyAttrNoIr
	// FrequencyAttrGoConcurrent as defined in nl80211/nl80211.h:3861
	FrequencyAttrGoConcurrent = FrequencyAttrIrConcurrent
	// AttrSchedScanMatchSsid as defined in nl80211/nl80211.h:4025
	AttrSchedScanMatchSsid = SchedScanMatchAttrSsid
	// RrfPassiveScan as defined in nl80211/nl80211.h:4069
	RrfPassiveScan = RrfNoIr
	// RrfNoIbss as defined in nl80211/nl80211.h:4070
	RrfNoIbss = RrfNoIr
	// RrfNoHt40 as defined in nl80211/nl80211.h:4072
	RrfNoHt40 = (RrfNoHt40minus | RrfNoHt40plus)
	// RrfGoConcurrent as defined in nl80211/nl80211.h:4074
	RrfGoConcurrent = RrfIrConcurrent
	// RrfNoIrAll as defined in nl80211/nl80211.h:4077
	RrfNoIrAll = (RrfNoIr | __RrfNoIbss)
	// SurveyInfoChannelTime as defined in nl80211/nl80211.h:4168
	SurveyInfoChannelTime = SurveyInfoTime
	// SurveyInfoChannelTimeBusy as defined in nl80211/nl80211.h:4169
	SurveyInfoChannelTimeBusy = SurveyInfoTimeBusy
	// SurveyInfoChannelTimeExtBusy as defined in nl80211/nl80211.h:4170
	SurveyInfoChannelTimeExtBusy = SurveyInfoTimeExtBusy
	// SurveyInfoChannelTimeRx as defined in nl80211/nl80211.h:4171
	SurveyInfoChannelTimeRx = SurveyInfoTimeRx
	// SurveyInfoChannelTimeTx as defined in nl80211/nl80211.h:4172
	SurveyInfoChannelTimeTx = SurveyInfoTimeTx
	// TxqAttrQueue as defined in nl80211/nl80211.h:4498
	TxqAttrQueue = TxqAttrAc
	// TxqQVo as defined in nl80211/nl80211.h:4499
	TxqQVo = AcVo
	// TxqQVi as defined in nl80211/nl80211.h:4500
	TxqQVi = AcVi
	// TxqQBe as defined in nl80211/nl80211.h:4501
	TxqQBe = AcBe
	// TxqQBk as defined in nl80211/nl80211.h:4502
	TxqQBk = AcBk
	// TxrateMcs as defined in nl80211/nl80211.h:4860
	TxrateMcs = TxrateHt
	// VhtNssMax as defined in nl80211/nl80211.h:4861
	VhtNssMax = 8
	// HeNssMax as defined in nl80211/nl80211.h:4871
	HeNssMax = 8
	// __WowlanPktpatInvalid as defined in nl80211/nl80211.h:5131
	__WowlanPktpatInvalid = __PktpatInvalid
	// WowlanPktpatMask as defined in nl80211/nl80211.h:5132
	WowlanPktpatMask = PktpatMask
	// WowlanPktpatPattern as defined in nl80211/nl80211.h:5133
	WowlanPktpatPattern = PktpatPattern
	// WowlanPktpatOffset as defined in nl80211/nl80211.h:5134
	WowlanPktpatOffset = PktpatOffset
	// Num_WowlanPktpat as defined in nl80211/nl80211.h:5135
	Num_WowlanPktpat = Num_Pktpat
	// Max_WowlanPktpat as defined in nl80211/nl80211.h:5136
	Max_WowlanPktpat = Max_Pktpat
	// WowlanPatternSupport as defined in nl80211/nl80211.h:5137
	WowlanPatternSupport = 0
	// KckLen as defined in nl80211/nl80211.h:5548
	KckLen = 16
	// KekLen as defined in nl80211/nl80211.h:5549
	KekLen = 16
	// KckExtLen as defined in nl80211/nl80211.h:5550
	KckExtLen = 24
	// KekExtLen as defined in nl80211/nl80211.h:5551
	KekExtLen = 32
	// ReplayCtrLen as defined in nl80211/nl80211.h:5552
	ReplayCtrLen = 8
	// CritProtoMaxDuration as defined in nl80211/nl80211.h:6270
	CritProtoMaxDuration = 5000
	// VendorIdIsLinux as defined in nl80211/nl80211.h:6293
	VendorIdIsLinux = 0x80000000
	// NanFuncServiceIdLen as defined in nl80211/nl80211.h:6442
	NanFuncServiceIdLen = 6
	// NanFuncServiceSpecInfoMaxLen as defined in nl80211/nl80211.h:6443
	NanFuncServiceSpecInfoMaxLen = 0xff
	// NanFuncSrfMaxLen as defined in nl80211/nl80211.h:6444
	NanFuncSrfMaxLen = 0xff
	// FilsDiscoveryTmplMinLen as defined in nl80211/nl80211.h:7170
	FilsDiscoveryTmplMinLen = 42
)

// nl80211Commands as declared in nl80211/nl80211.h:1191
type nl80211Commands int32

// nl80211Commands enumeration from nl80211/nl80211.h:1191
const (
	CmdUnspec                   = iota
	CmdGetWiphy                 = 1
	CmdSetWiphy                 = 2
	CmdNewWiphy                 = 3
	CmdDelWiphy                 = 4
	CmdGetInterface             = 5
	CmdSetInterface             = 6
	CmdNewInterface             = 7
	CmdDelInterface             = 8
	CmdGetKey                   = 9
	CmdSetKey                   = 10
	CmdNewKey                   = 11
	CmdDelKey                   = 12
	CmdGetBeacon                = 13
	CmdSetBeacon                = 14
	CmdStartAp                  = 15
	CmdNewBeacon                = CmdStartAp
	CmdStopAp                   = 16
	CmdDelBeacon                = CmdStopAp
	CmdGetStation               = 17
	CmdSetStation               = 18
	CmdNewStation               = 19
	CmdDelStation               = 20
	CmdGetMpath                 = 21
	CmdSetMpath                 = 22
	CmdNewMpath                 = 23
	CmdDelMpath                 = 24
	CmdSetBss                   = 25
	CmdSetReg                   = 26
	CmdReqSetReg                = 27
	CmdGetMeshConfig            = 28
	CmdSetMeshConfig            = 29
	CmdSetMgmtExtraIe           = 30
	CmdGetReg                   = 31
	CmdGetScan                  = 32
	CmdTriggerScan              = 33
	CmdNewScanResults           = 34
	CmdScanAborted              = 35
	CmdRegChange                = 36
	CmdAuthenticate             = 37
	CmdAssociate                = 38
	CmdDeauthenticate           = 39
	CmdDisassociate             = 40
	CmdMichaelMicFailure        = 41
	CmdRegBeaconHint            = 42
	CmdJoinIbss                 = 43
	CmdLeaveIbss                = 44
	CmdTestmode                 = 45
	CmdConnect                  = 46
	CmdRoam                     = 47
	CmdDisconnect               = 48
	CmdSetWiphyNetns            = 49
	CmdGetSurvey                = 50
	CmdNewSurveyResults         = 51
	CmdSetPmksa                 = 52
	CmdDelPmksa                 = 53
	CmdFlushPmksa               = 54
	CmdRemainOnChannel          = 55
	CmdCancelRemainOnChannel    = 56
	CmdSetTxBitrateMask         = 57
	CmdRegisterFrame            = 58
	CmdRegisterAction           = CmdRegisterFrame
	CmdFrame                    = 59
	CmdAction                   = CmdFrame
	CmdFrameTxStatus            = 60
	CmdActionTxStatus           = CmdFrameTxStatus
	CmdSetPowerSave             = 61
	CmdGetPowerSave             = 62
	CmdSetCqm                   = 63
	CmdNotifyCqm                = 64
	CmdSetChannel               = 65
	CmdSetWdsPeer               = 66
	CmdFrameWaitCancel          = 67
	CmdJoinMesh                 = 68
	CmdLeaveMesh                = 69
	CmdUnprotDeauthenticate     = 70
	CmdUnprotDisassociate       = 71
	CmdNewPeerCandidate         = 72
	CmdGetWowlan                = 73
	CmdSetWowlan                = 74
	CmdStartSchedScan           = 75
	CmdStopSchedScan            = 76
	CmdSchedScanResults         = 77
	CmdSchedScanStopped         = 78
	CmdSetRekeyOffload          = 79
	CmdPmksaCandidate           = 80
	CmdTdlsOper                 = 81
	CmdTdlsMgmt                 = 82
	CmdUnexpectedFrame          = 83
	CmdProbeClient              = 84
	CmdRegisterBeacons          = 85
	CmdUnexpected4addrFrame     = 86
	CmdSetNoackMap              = 87
	CmdChSwitchNotify           = 88
	CmdStartP2pDevice           = 89
	CmdStopP2pDevice            = 90
	CmdConnFailed               = 91
	CmdSetMcastRate             = 92
	CmdSetMacAcl                = 93
	CmdRadarDetect              = 94
	CmdGetProtocolFeatures      = 95
	CmdUpdateFtIes              = 96
	CmdFtEvent                  = 97
	CmdCritProtocolStart        = 98
	CmdCritProtocolStop         = 99
	CmdGetCoalesce              = 100
	CmdSetCoalesce              = 101
	CmdChannelSwitch            = 102
	CmdVendor                   = 103
	CmdSetQosMap                = 104
	CmdAddTxTs                  = 105
	CmdDelTxTs                  = 106
	CmdGetMpp                   = 107
	CmdJoinOcb                  = 108
	CmdLeaveOcb                 = 109
	CmdChSwitchStartedNotify    = 110
	CmdTdlsChannelSwitch        = 111
	CmdTdlsCancelChannelSwitch  = 112
	CmdWiphyRegChange           = 113
	CmdAbortScan                = 114
	CmdStartNan                 = 115
	CmdStopNan                  = 116
	CmdAddNanFunction           = 117
	CmdDelNanFunction           = 118
	CmdChangeNanConfig          = 119
	CmdNanMatch                 = 120
	CmdSetMulticastToUnicast    = 121
	CmdUpdateConnectParams      = 122
	CmdSetPmk                   = 123
	CmdDelPmk                   = 124
	CmdPortAuthorized           = 125
	CmdReloadRegdb              = 126
	CmdExternalAuth             = 127
	CmdStaOpmodeChanged         = 128
	CmdControlPortFrame         = 129
	CmdGetFtmResponderStats     = 130
	CmdPeerMeasurementStart     = 131
	CmdPeerMeasurementResult    = 132
	CmdPeerMeasurementComplete  = 133
	CmdNotifyRadar              = 134
	CmdUpdateOweInfo            = 135
	CmdProbeMeshLink            = 136
	CmdSetTidConfig             = 137
	CmdUnprotBeacon             = 138
	CmdControlPortFrameTxStatus = 139
	CmdSetSarSpecs              = 140
	__CmdAfterLast              = 141
	CmdMax                      = __CmdAfterLast - 1
)

// nl80211Attrs as declared in nl80211/nl80211.h:2567
type nl80211Attrs int32

// nl80211Attrs enumeration from nl80211/nl80211.h:2567
const (
	AttrUnspec                       = iota
	AttrWiphy                        = 1
	AttrWiphyName                    = 2
	AttrIfindex                      = 3
	AttrIfname                       = 4
	AttrIftype                       = 5
	AttrMac                          = 6
	AttrKeyData                      = 7
	AttrKeyIdx                       = 8
	AttrKeyCipher                    = 9
	AttrKeySeq                       = 10
	AttrKeyDefault                   = 11
	AttrBeaconInterval               = 12
	AttrDtimPeriod                   = 13
	AttrBeaconHead                   = 14
	AttrBeaconTail                   = 15
	AttrStaAid                       = 16
	AttrStaFlags                     = 17
	AttrStaListenInterval            = 18
	AttrStaSupportedRates            = 19
	AttrStaVlan                      = 20
	AttrStaInfo                      = 21
	AttrWiphyBands                   = 22
	AttrMntrFlags                    = 23
	AttrMeshId                       = 24
	AttrStaPlinkAction               = 25
	AttrMpathNextHop                 = 26
	AttrMpathInfo                    = 27
	AttrBssCtsProt                   = 28
	AttrBssShortPreamble             = 29
	AttrBssShortSlotTime             = 30
	AttrHtCapability                 = 31
	AttrSupportedIftypes             = 32
	AttrRegAlpha2                    = 33
	AttrRegRules                     = 34
	AttrMeshConfig                   = 35
	AttrBssBasicRates                = 36
	AttrWiphyTxqParams               = 37
	AttrWiphyFreq                    = 38
	AttrWiphyChannelType             = 39
	AttrKeyDefaultMgmt               = 40
	AttrMgmtSubtype                  = 41
	AttrIe                           = 42
	AttrMaxNumScanSsids              = 43
	AttrScanFrequencies              = 44
	AttrScanSsids                    = 45
	AttrGeneration                   = 46
	AttrBss                          = 47
	AttrRegInitiator                 = 48
	AttrRegType                      = 49
	AttrSupportedCommands            = 50
	AttrFrame                        = 51
	AttrSsid                         = 52
	AttrAuthType                     = 53
	AttrReasonCode                   = 54
	AttrKeyType                      = 55
	AttrMaxScanIeLen                 = 56
	AttrCipherSuites                 = 57
	AttrFreqBefore                   = 58
	AttrFreqAfter                    = 59
	AttrFreqFixed                    = 60
	AttrWiphyRetryShort              = 61
	AttrWiphyRetryLong               = 62
	AttrWiphyFragThreshold           = 63
	AttrWiphyRtsThreshold            = 64
	AttrTimedOut                     = 65
	AttrUseMfp                       = 66
	AttrStaFlags2                    = 67
	AttrControlPort                  = 68
	AttrTestdata                     = 69
	AttrPrivacy                      = 70
	AttrDisconnectedByAp             = 71
	AttrStatusCode                   = 72
	AttrCipherSuitesPairwise         = 73
	AttrCipherSuiteGroup             = 74
	AttrWpaVersions                  = 75
	AttrAkmSuites                    = 76
	AttrReqIe                        = 77
	AttrRespIe                       = 78
	AttrPrevBssid                    = 79
	AttrKey                          = 80
	AttrKeys                         = 81
	AttrPid                          = 82
	Attr4addr                        = 83
	AttrSurveyInfo                   = 84
	AttrPmkid                        = 85
	AttrMaxNumPmkids                 = 86
	AttrDuration                     = 87
	AttrCookie                       = 88
	AttrWiphyCoverageClass           = 89
	AttrTxRates                      = 90
	AttrFrameMatch                   = 91
	AttrAck                          = 92
	AttrPsState                      = 93
	AttrCqm                          = 94
	AttrLocalStateChange             = 95
	AttrApIsolate                    = 96
	AttrWiphyTxPowerSetting          = 97
	AttrWiphyTxPowerLevel            = 98
	AttrTxFrameTypes                 = 99
	AttrRxFrameTypes                 = 100
	AttrFrameType                    = 101
	AttrControlPortEthertype         = 102
	AttrControlPortNoEncrypt         = 103
	AttrSupportIbssRsn               = 104
	AttrWiphyAntennaTx               = 105
	AttrWiphyAntennaRx               = 106
	AttrMcastRate                    = 107
	AttrOffchannelTxOk               = 108
	AttrBssHtOpmode                  = 109
	AttrKeyDefaultTypes              = 110
	AttrMaxRemainOnChannelDuration   = 111
	AttrMeshSetup                    = 112
	AttrWiphyAntennaAvailTx          = 113
	AttrWiphyAntennaAvailRx          = 114
	AttrSupportMeshAuth              = 115
	AttrStaPlinkState                = 116
	AttrWowlanTriggers               = 117
	AttrWowlanTriggersSupported      = 118
	AttrSchedScanInterval            = 119
	AttrInterfaceCombinations        = 120
	AttrSoftwareIftypes              = 121
	AttrRekeyData                    = 122
	AttrMaxNumSchedScanSsids         = 123
	AttrMaxSchedScanIeLen            = 124
	AttrScanSuppRates                = 125
	AttrHiddenSsid                   = 126
	AttrIeProbeResp                  = 127
	AttrIeAssocResp                  = 128
	AttrStaWme                       = 129
	AttrSupportApUapsd               = 130
	AttrRoamSupport                  = 131
	AttrSchedScanMatch               = 132
	AttrMaxMatchSets                 = 133
	AttrPmksaCandidate               = 134
	AttrTxNoCckRate                  = 135
	AttrTdlsAction                   = 136
	AttrTdlsDialogToken              = 137
	AttrTdlsOperation                = 138
	AttrTdlsSupport                  = 139
	AttrTdlsExternalSetup            = 140
	AttrDeviceApSme                  = 141
	AttrDontWaitForAck               = 142
	AttrFeatureFlags                 = 143
	AttrProbeRespOffload             = 144
	AttrProbeResp                    = 145
	AttrDfsRegion                    = 146
	AttrDisableHt                    = 147
	AttrHtCapabilityMask             = 148
	AttrNoackMap                     = 149
	AttrInactivityTimeout            = 150
	AttrRxSignalDbm                  = 151
	AttrBgScanPeriod                 = 152
	AttrWdev                         = 153
	AttrUserRegHintType              = 154
	AttrConnFailedReason             = 155
	AttrAuthData                     = 156
	AttrVhtCapability                = 157
	AttrScanFlags                    = 158
	AttrChannelWidth                 = 159
	AttrCenterFreq1                  = 160
	AttrCenterFreq2                  = 161
	AttrP2pCtwindow                  = 162
	AttrP2pOppps                     = 163
	AttrLocalMeshPowerMode           = 164
	AttrAclPolicy                    = 165
	AttrMacAddrs                     = 166
	AttrMacAclMax                    = 167
	AttrRadarEvent                   = 168
	AttrExtCapa                      = 169
	AttrExtCapaMask                  = 170
	AttrStaCapability                = 171
	AttrStaExtCapability             = 172
	AttrProtocolFeatures             = 173
	AttrSplitWiphyDump               = 174
	AttrDisableVht                   = 175
	AttrVhtCapabilityMask            = 176
	AttrMdid                         = 177
	AttrIeRic                        = 178
	AttrCritProtId                   = 179
	AttrMaxCritProtDuration          = 180
	AttrPeerAid                      = 181
	AttrCoalesceRule                 = 182
	AttrChSwitchCount                = 183
	AttrChSwitchBlockTx              = 184
	AttrCsaIes                       = 185
	AttrCntdwnOffsBeacon             = 186
	AttrCntdwnOffsPresp              = 187
	AttrRxmgmtFlags                  = 188
	AttrStaSupportedChannels         = 189
	AttrStaSupportedOperClasses      = 190
	AttrHandleDfs                    = 191
	AttrSupport5Mhz                  = 192
	AttrSupport10Mhz                 = 193
	AttrOpmodeNotif                  = 194
	AttrVendorId                     = 195
	AttrVendorSubcmd                 = 196
	AttrVendorData                   = 197
	AttrVendorEvents                 = 198
	AttrQosMap                       = 199
	AttrMacHint                      = 200
	AttrWiphyFreqHint                = 201
	AttrMaxApAssocSta                = 202
	AttrTdlsPeerCapability           = 203
	AttrSocketOwner                  = 204
	AttrCsaCOffsetsTx                = 205
	AttrMaxCsaCounters               = 206
	AttrTdlsInitiator                = 207
	AttrUseRrm                       = 208
	AttrWiphyDynAck                  = 209
	AttrTsid                         = 210
	AttrUserPrio                     = 211
	AttrAdmittedTime                 = 212
	AttrSmpsMode                     = 213
	AttrOperClass                    = 214
	AttrMacMask                      = 215
	AttrWiphySelfManagedReg          = 216
	AttrExtFeatures                  = 217
	AttrSurveyRadioStats             = 218
	AttrNetnsFd                      = 219
	AttrSchedScanDelay               = 220
	AttrRegIndoor                    = 221
	AttrMaxNumSchedScanPlans         = 222
	AttrMaxScanPlanInterval          = 223
	AttrMaxScanPlanIterations        = 224
	AttrSchedScanPlans               = 225
	AttrPbss                         = 226
	AttrBssSelect                    = 227
	AttrStaSupportP2pPs              = 228
	AttrPad                          = 229
	AttrIftypeExtCapa                = 230
	AttrMuMimoGroupData              = 231
	AttrMuMimoFollowMacAddr          = 232
	AttrScanStartTimeTsf             = 233
	AttrScanStartTimeTsfBssid        = 234
	AttrMeasurementDuration          = 235
	AttrMeasurementDurationMandatory = 236
	AttrMeshPeerAid                  = 237
	AttrNanMasterPref                = 238
	AttrBands                        = 239
	AttrNanFunc                      = 240
	AttrNanMatch                     = 241
	AttrFilsKek                      = 242
	AttrFilsNonces                   = 243
	AttrMulticastToUnicastEnabled    = 244
	AttrBssid                        = 245
	AttrSchedScanRelativeRssi        = 246
	AttrSchedScanRssiAdjust          = 247
	AttrTimeoutReason                = 248
	AttrFilsErpUsername              = 249
	AttrFilsErpRealm                 = 250
	AttrFilsErpNextSeqNum            = 251
	AttrFilsErpRrk                   = 252
	AttrFilsCacheId                  = 253
	AttrPmk                          = 254
	AttrSchedScanMulti               = 255
	AttrSchedScanMaxReqs             = 256
	AttrWant1x4wayHs                 = 257
	AttrPmkr0Name                    = 258
	AttrPortAuthorized               = 259
	AttrExternalAuthAction           = 260
	AttrExternalAuthSupport          = 261
	AttrNss                          = 262
	AttrAckSignal                    = 263
	AttrControlPortOverNl80211       = 264
	AttrTxqStats                     = 265
	AttrTxqLimit                     = 266
	AttrTxqMemoryLimit               = 267
	AttrTxqQuantum                   = 268
	AttrHeCapability                 = 269
	AttrFtmResponder                 = 270
	AttrFtmResponderStats            = 271
	AttrTimeout                      = 272
	AttrPeerMeasurements             = 273
	AttrAirtimeWeight                = 274
	AttrStaTxPowerSetting            = 275
	AttrStaTxPower                   = 276
	AttrSaePassword                  = 277
	AttrTwtResponder                 = 278
	AttrHeObssPd                     = 279
	AttrWiphyEdmgChannels            = 280
	AttrWiphyEdmgBwConfig            = 281
	AttrVlanId                       = 282
	AttrHeBssColor                   = 283
	AttrIftypeAkmSuites              = 284
	AttrTidConfig                    = 285
	AttrControlPortNoPreauth         = 286
	AttrPmkLifetime                  = 287
	AttrPmkReauthThreshold           = 288
	AttrReceiveMulticast             = 289
	AttrWiphyFreqOffset              = 290
	AttrCenterFreq1Offset            = 291
	AttrScanFreqKhz                  = 292
	AttrHe6ghzCapability             = 293
	AttrFilsDiscovery                = 294
	AttrUnsolBcastProbeResp          = 295
	AttrS1gCapability                = 296
	AttrS1gCapabilityMask            = 297
	AttrSaePwe                       = 298
	AttrReconnectRequested           = 299
	AttrSarSpec                      = 300
	AttrDisableHe                    = 301
	__AttrAfterLast                  = 302
	Num_Attr                         = __AttrAfterLast
	AttrMax                          = __AttrAfterLast - 1
)

// nl80211Iftype as declared in nl80211/nl80211.h:3152
type nl80211Iftype int32

// nl80211Iftype enumeration from nl80211/nl80211.h:3152
const (
	IftypeUnspecified = iota
	IftypeAdhoc       = 1
	IftypeStation     = 2
	IftypeAp          = 3
	IftypeApVlan      = 4
	IftypeWds         = 5
	IftypeMonitor     = 6
	IftypeMeshPoint   = 7
	IftypeP2pClient   = 8
	IftypeP2pGo       = 9
	IftypeP2pDevice   = 10
	IftypeOcb         = 11
	IftypeNan         = 12
	Num_Iftypes       = 13
	IftypeMax         = Num_Iftypes - 1
)

// nl80211StaFlags as declared in nl80211/nl80211.h:3196
type nl80211StaFlags int32

// nl80211StaFlags enumeration from nl80211/nl80211.h:3196
const (
	__StaFlagInvalid     = iota
	StaFlagAuthorized    = 1
	StaFlagShortPreamble = 2
	StaFlagWme           = 3
	StaFlagMfp           = 4
	StaFlagAuthenticated = 5
	StaFlagTdlsPeer      = 6
	StaFlagAssociated    = 7
	__StaFlagAfterLast   = 8
	StaFlagMax           = __StaFlagAfterLast - 1
)

// nl80211StaP2pPsStatus as declared in nl80211/nl80211.h:3218
type nl80211StaP2pPsStatus int32

// nl80211StaP2pPsStatus enumeration from nl80211/nl80211.h:3218
const (
	P2pPsUnsupported = iota
	P2pPsSupported   = 1
	Num_P2pPsStatus  = 2
)

// nl80211HeGi as declared in nl80211/nl80211.h:3245
type nl80211HeGi int32

// nl80211HeGi enumeration from nl80211/nl80211.h:3245
const (
	RateInfoHeGi08 = iota
	RateInfoHeGi16 = 1
	RateInfoHeGi32 = 2
)

// nl80211HeLtf as declared in nl80211/nl80211.h:3257
type nl80211HeLtf int32

// nl80211HeLtf enumeration from nl80211/nl80211.h:3257
const (
	RateInfoHe1xltf = iota
	RateInfoHe2xltf = 1
	RateInfoHe4xltf = 2
)

// nl80211HeRuAlloc as declared in nl80211/nl80211.h:3273
type nl80211HeRuAlloc int32

// nl80211HeRuAlloc enumeration from nl80211/nl80211.h:3273
const (
	RateInfoHeRuAlloc26    = iota
	RateInfoHeRuAlloc52    = 1
	RateInfoHeRuAlloc106   = 2
	RateInfoHeRuAlloc242   = 3
	RateInfoHeRuAlloc484   = 4
	RateInfoHeRuAlloc996   = 5
	RateInfoHeRuAlloc2x996 = 6
)

// nl80211RateInfo as declared in nl80211/nl80211.h:3324
type nl80211RateInfo int32

// nl80211RateInfo enumeration from nl80211/nl80211.h:3324
const (
	__RateInfoInvalid     = iota
	RateInfoBitrate       = 1
	RateInfoMcs           = 2
	RateInfo40MhzWidth    = 3
	RateInfoShortGi       = 4
	RateInfoBitrate32     = 5
	RateInfoVhtMcs        = 6
	RateInfoVhtNss        = 7
	RateInfo80MhzWidth    = 8
	RateInfo80p80MhzWidth = 9
	RateInfo160MhzWidth   = 10
	RateInfo10MhzWidth    = 11
	RateInfo5MhzWidth     = 12
	RateInfoHeMcs         = 13
	RateInfoHeNss         = 14
	RateInfoHeGi          = 15
	RateInfoHeDcm         = 16
	RateInfoHeRuAlloc     = 17
	__RateInfoAfterLast   = 18
	RateInfoMax           = __RateInfoAfterLast - 1
)

// nl80211StaBssParam as declared in nl80211/nl80211.h:3366
type nl80211StaBssParam int32

// nl80211StaBssParam enumeration from nl80211/nl80211.h:3366
const (
	__StaBssParamInvalid      = iota
	StaBssParamCtsProt        = 1
	StaBssParamShortPreamble  = 2
	StaBssParamShortSlotTime  = 3
	StaBssParamDtimPeriod     = 4
	StaBssParamBeaconInterval = 5
	__StaBssParamAfterLast    = 6
	StaBssParamMax            = __StaBssParamAfterLast - 1
)

// nl80211StaInfo as declared in nl80211/nl80211.h:3462
type nl80211StaInfo int32

// nl80211StaInfo enumeration from nl80211/nl80211.h:3462
const (
	__StaInfoInvalid          = iota
	StaInfoInactiveTime       = 1
	StaInfoRxBytes            = 2
	StaInfoTxBytes            = 3
	StaInfoLlid               = 4
	StaInfoPlid               = 5
	StaInfoPlinkState         = 6
	StaInfoSignal             = 7
	StaInfoTxBitrate          = 8
	StaInfoRxPackets          = 9
	StaInfoTxPackets          = 10
	StaInfoTxRetries          = 11
	StaInfoTxFailed           = 12
	StaInfoSignalAvg          = 13
	StaInfoRxBitrate          = 14
	StaInfoBssParam           = 15
	StaInfoConnectedTime      = 16
	StaInfoStaFlags           = 17
	StaInfoBeaconLoss         = 18
	StaInfoTOffset            = 19
	StaInfoLocalPm            = 20
	StaInfoPeerPm             = 21
	StaInfoNonpeerPm          = 22
	StaInfoRxBytes64          = 23
	StaInfoTxBytes64          = 24
	StaInfoChainSignal        = 25
	StaInfoChainSignalAvg     = 26
	StaInfoExpectedThroughput = 27
	StaInfoRxDropMisc         = 28
	StaInfoBeaconRx           = 29
	StaInfoBeaconSignalAvg    = 30
	StaInfoTidStats           = 31
	StaInfoRxDuration         = 32
	StaInfoPad                = 33
	StaInfoAckSignal          = 34
	StaInfoAckSignalAvg       = 35
	StaInfoRxMpdus            = 36
	StaInfoFcsErrorCount      = 37
	StaInfoConnectedToGate    = 38
	StaInfoTxDuration         = 39
	StaInfoAirtimeWeight      = 40
	StaInfoAirtimeLinkMetric  = 41
	StaInfoAssocAtBoottime    = 42
	StaInfoConnectedToAs      = 43
	__StaInfoAfterLast        = 44
	StaInfoMax                = __StaInfoAfterLast - 1
)

// nl80211TidStats as declared in nl80211/nl80211.h:3532
type nl80211TidStats int32

// nl80211TidStats enumeration from nl80211/nl80211.h:3532
const (
	__TidStatsInvalid     = iota
	TidStatsRxMsdu        = 1
	TidStatsTxMsdu        = 2
	TidStatsTxMsduRetries = 3
	TidStatsTxMsduFailed  = 4
	TidStatsPad           = 5
	TidStatsTxqStats      = 6
	Num_TidStats          = 7
	TidStatsMax           = Num_TidStats - 1
)

// nl80211TxqStats as declared in nl80211/nl80211.h:3565
type nl80211TxqStats int32

// nl80211TxqStats enumeration from nl80211/nl80211.h:3565
const (
	__TxqStatsInvalid      = iota
	TxqStatsBacklogBytes   = 1
	TxqStatsBacklogPackets = 2
	TxqStatsFlows          = 3
	TxqStatsDrops          = 4
	TxqStatsEcnMarks       = 5
	TxqStatsOverlimit      = 6
	TxqStatsOvermemory     = 7
	TxqStatsCollisions     = 8
	TxqStatsTxBytes        = 9
	TxqStatsTxPackets      = 10
	TxqStatsMaxFlows       = 11
	Num_TxqStats           = 12
	TxqStatsMax            = Num_TxqStats - 1
)

// nl80211MpathFlags as declared in nl80211/nl80211.h:3593
type nl80211MpathFlags int32

// nl80211MpathFlags enumeration from nl80211/nl80211.h:3593
const (
	MpathFlagActive    = 1 << 0
	MpathFlagResolving = 1 << 1
	MpathFlagSnValid   = 1 << 2
	MpathFlagFixed     = 1 << 3
	MpathFlagResolved  = 1 << 4
)

// nl80211MpathInfo as declared in nl80211/nl80211.h:3622
type nl80211MpathInfo int32

// nl80211MpathInfo enumeration from nl80211/nl80211.h:3622
const (
	__MpathInfoInvalid        = iota
	MpathInfoFrameQlen        = 1
	MpathInfoSn               = 2
	MpathInfoMetric           = 3
	MpathInfoExptime          = 4
	MpathInfoFlags            = 5
	MpathInfoDiscoveryTimeout = 6
	MpathInfoDiscoveryRetries = 7
	MpathInfoHopCount         = 8
	MpathInfoPathChange       = 9
	__MpathInfoAfterLast      = 10
	MpathInfoMax              = __MpathInfoAfterLast - 1
)

// nl80211BandIftypeAttr as declared in nl80211/nl80211.h:3661
type nl80211BandIftypeAttr int32

// nl80211BandIftypeAttr enumeration from nl80211/nl80211.h:3661
const (
	__BandIftypeAttrInvalid   = iota
	BandIftypeAttrIftypes     = 1
	BandIftypeAttrHeCapMac    = 2
	BandIftypeAttrHeCapPhy    = 3
	BandIftypeAttrHeCapMcsSet = 4
	BandIftypeAttrHeCapPpe    = 5
	BandIftypeAttrHe6ghzCapa  = 6
	BandIftypeAttrVendorElems = 7
	__BandIftypeAttrAfterLast = 8
	BandIftypeAttrMax         = __BandIftypeAttrAfterLast - 1
)

// nl80211BandAttr as declared in nl80211/nl80211.h:3703
type nl80211BandAttr int32

// nl80211BandAttr enumeration from nl80211/nl80211.h:3703
const (
	__BandAttrInvalid      = iota
	BandAttrFreqs          = 1
	BandAttrRates          = 2
	BandAttrHtMcsSet       = 3
	BandAttrHtCapa         = 4
	BandAttrHtAmpduFactor  = 5
	BandAttrHtAmpduDensity = 6
	BandAttrVhtMcsSet      = 7
	BandAttrVhtCapa        = 8
	BandAttrIftypeData     = 9
	BandAttrEdmgChannels   = 10
	BandAttrEdmgBwConfig   = 11
	__BandAttrAfterLast    = 12
	BandAttrMax            = __BandAttrAfterLast - 1
)

// nl80211WmmRule as declared in nl80211/nl80211.h:3738
type nl80211WmmRule int32

// nl80211WmmRule enumeration from nl80211/nl80211.h:3738
const (
	__WmmrInvalid = iota
	WmmrCwMin     = 1
	WmmrCwMax     = 2
	WmmrAifsn     = 3
	WmmrTxop      = 4
	__WmmrLast    = 5
	WmmrMax       = __WmmrLast - 1
)

// nl80211FrequencyAttr as declared in nl80211/nl80211.h:3824
type nl80211FrequencyAttr int32

// nl80211FrequencyAttr enumeration from nl80211/nl80211.h:3824
const (
	__FrequencyAttrInvalid    = iota
	FrequencyAttrFreq         = 1
	FrequencyAttrDisabled     = 2
	FrequencyAttrNoIr         = 3
	__FrequencyAttrNoIbss     = 4
	FrequencyAttrRadar        = 5
	FrequencyAttrMaxTxPower   = 6
	FrequencyAttrDfsState     = 7
	FrequencyAttrDfsTime      = 8
	FrequencyAttrNoHt40Minus  = 9
	FrequencyAttrNoHt40Plus   = 10
	FrequencyAttrNo80mhz      = 11
	FrequencyAttrNo160mhz     = 12
	FrequencyAttrDfsCacTime   = 13
	FrequencyAttrIndoorOnly   = 14
	FrequencyAttrIrConcurrent = 15
	FrequencyAttrNo20mhz      = 16
	FrequencyAttrNo10mhz      = 17
	FrequencyAttrWmm          = 18
	FrequencyAttrNoHe         = 19
	FrequencyAttrOffset       = 20
	FrequencyAttr1mhz         = 21
	FrequencyAttr2mhz         = 22
	FrequencyAttr4mhz         = 23
	FrequencyAttr8mhz         = 24
	FrequencyAttr16mhz        = 25
	__FrequencyAttrAfterLast  = 26
	FrequencyAttrMax          = __FrequencyAttrAfterLast - 1
)

// nl80211BitrateAttr as declared in nl80211/nl80211.h:3874
type nl80211BitrateAttr int32

// nl80211BitrateAttr enumeration from nl80211/nl80211.h:3874
const (
	__BitrateAttrInvalid         = iota
	BitrateAttrRate              = 1
	BitrateAttr2ghzShortpreamble = 2
	__BitrateAttrAfterLast       = 3
	BitrateAttrMax               = __BitrateAttrAfterLast - 1
)

// nl80211RegInitiator as declared in nl80211/nl80211.h:3900
type nl80211RegInitiator int32

// nl80211RegInitiator enumeration from nl80211/nl80211.h:3900
const (
	RegdomSetByCore      = iota
	RegdomSetByUser      = 1
	RegdomSetByDriver    = 2
	RegdomSetByCountryIe = 3
)

// nl80211RegType as declared in nl80211/nl80211.h:3923
type nl80211RegType int32

// nl80211RegType enumeration from nl80211/nl80211.h:3923
const (
	RegdomTypeCountry      = iota
	RegdomTypeWorld        = 1
	RegdomTypeCustomWorld  = 2
	RegdomTypeIntersection = 3
)

// nl80211RegRuleAttr as declared in nl80211/nl80211.h:3955
type nl80211RegRuleAttr int32

// nl80211RegRuleAttr enumeration from nl80211/nl80211.h:3955
const (
	__RegRuleAttrInvalid    = iota
	AttrRegRuleFlags        = 1
	AttrFreqRangeStart      = 2
	AttrFreqRangeEnd        = 3
	AttrFreqRangeMaxBw      = 4
	AttrPowerRuleMaxAntGain = 5
	AttrPowerRuleMaxEirp    = 6
	AttrDfsCacTime          = 7
	__RegRuleAttrAfterLast  = 8
	RegRuleAttrMax          = __RegRuleAttrAfterLast - 1
)

// nl80211SchedScanMatchAttr as declared in nl80211/nl80211.h:4008
type nl80211SchedScanMatchAttr int32

// nl80211SchedScanMatchAttr enumeration from nl80211/nl80211.h:4008
const (
	__SchedScanMatchAttrInvalid    = iota
	SchedScanMatchAttrSsid         = 1
	SchedScanMatchAttrRssi         = 2
	SchedScanMatchAttrRelativeRssi = 3
	SchedScanMatchAttrRssiAdjust   = 4
	SchedScanMatchAttrBssid        = 5
	SchedScanMatchPerBandRssi      = 6
	__SchedScanMatchAttrAfterLast  = 7
	SchedScanMatchAttrMax          = __SchedScanMatchAttrAfterLast - 1
)

// nl80211RegRuleFlags as declared in nl80211/nl80211.h:4050
type nl80211RegRuleFlags int32

// nl80211RegRuleFlags enumeration from nl80211/nl80211.h:4050
const (
	RrfNoOfdm       = 1 << 0
	RrfNoCck        = 1 << 1
	RrfNoIndoor     = 1 << 2
	RrfNoOutdoor    = 1 << 3
	RrfDfs          = 1 << 4
	RrfPtpOnly      = 1 << 5
	RrfPtmpOnly     = 1 << 6
	RrfNoIr         = 1 << 7
	__RrfNoIbss     = 1 << 8
	RrfAutoBw       = 1 << 11
	RrfIrConcurrent = 1 << 12
	RrfNoHt40minus  = 1 << 13
	RrfNoHt40plus   = 1 << 14
	RrfNo80mhz      = 1 << 15
	RrfNo160mhz     = 1 << 16
	RrfNoHe         = 1 << 17
)

// nl80211DfsRegions as declared in nl80211/nl80211.h:4087
type nl80211DfsRegions int32

// nl80211DfsRegions enumeration from nl80211/nl80211.h:4087
const (
	DfsUnset = iota
	DfsFcc   = 1
	DfsEtsi  = 2
	DfsJp    = 3
)

// nl80211UserRegHintType as declared in nl80211/nl80211.h:4111
type nl80211UserRegHintType int32

// nl80211UserRegHintType enumeration from nl80211/nl80211.h:4111
const (
	UserRegHintUser     = iota
	UserRegHintCellBase = 1
	UserRegHintIndoor   = 2
)

// nl80211SurveyInfo as declared in nl80211/nl80211.h:4147
type nl80211SurveyInfo int32

// nl80211SurveyInfo enumeration from nl80211/nl80211.h:4147
const (
	__SurveyInfoInvalid       = iota
	SurveyInfoFrequency       = 1
	SurveyInfoNoise           = 2
	SurveyInfoInUse           = 3
	SurveyInfoTime            = 4
	SurveyInfoTimeBusy        = 5
	SurveyInfoTimeExtBusy     = 6
	SurveyInfoTimeRx          = 7
	SurveyInfoTimeTx          = 8
	SurveyInfoTimeScan        = 9
	SurveyInfoPad             = 10
	SurveyInfoTimeBssRx       = 11
	SurveyInfoFrequencyOffset = 12
	__SurveyInfoAfterLast     = 13
	SurveyInfoMax             = __SurveyInfoAfterLast - 1
)

// nl80211MntrFlags as declared in nl80211/nl80211.h:4193
type nl80211MntrFlags int32

// nl80211MntrFlags enumeration from nl80211/nl80211.h:4193
const (
	__MntrFlagInvalid   = iota
	MntrFlagFcsfail     = 1
	MntrFlagPlcpfail    = 2
	MntrFlagControl     = 3
	MntrFlagOtherBss    = 4
	MntrFlagCookFrames  = 5
	MntrFlagActive      = 6
	__MntrFlagAfterLast = 7
	MntrFlagMax         = __MntrFlagAfterLast - 1
)

// nl80211MeshPowerMode as declared in nl80211/nl80211.h:4225
type nl80211MeshPowerMode int32

// nl80211MeshPowerMode enumeration from nl80211/nl80211.h:4225
const (
	MeshPowerUnknown     = iota
	MeshPowerActive      = 1
	MeshPowerLightSleep  = 2
	MeshPowerDeepSleep   = 3
	__MeshPowerAfterLast = 4
	MeshPowerMax         = __MeshPowerAfterLast - 1
)

// nl80211MeshconfParams as declared in nl80211/nl80211.h:4358
type nl80211MeshconfParams int32

// nl80211MeshconfParams enumeration from nl80211/nl80211.h:4358
const (
	__MeshconfInvalid                = iota
	MeshconfRetryTimeout             = 1
	MeshconfConfirmTimeout           = 2
	MeshconfHoldingTimeout           = 3
	MeshconfMaxPeerLinks             = 4
	MeshconfMaxRetries               = 5
	MeshconfTtl                      = 6
	MeshconfAutoOpenPlinks           = 7
	MeshconfHwmpMaxPreqRetries       = 8
	MeshconfPathRefreshTime          = 9
	MeshconfMinDiscoveryTimeout      = 10
	MeshconfHwmpActivePathTimeout    = 11
	MeshconfHwmpPreqMinInterval      = 12
	MeshconfHwmpNetDiamTrvsTime      = 13
	MeshconfHwmpRootmode             = 14
	MeshconfElementTtl               = 15
	MeshconfHwmpRannInterval         = 16
	MeshconfGateAnnouncements        = 17
	MeshconfHwmpPerrMinInterval      = 18
	MeshconfForwarding               = 19
	MeshconfRssiThreshold            = 20
	MeshconfSyncOffsetMaxNeighbor    = 21
	MeshconfHtOpmode                 = 22
	MeshconfHwmpPathToRootTimeout    = 23
	MeshconfHwmpRootInterval         = 24
	MeshconfHwmpConfirmationInterval = 25
	MeshconfPowerMode                = 26
	MeshconfAwakeWindow              = 27
	MeshconfPlinkTimeout             = 28
	MeshconfConnectedToGate          = 29
	MeshconfNolearn                  = 30
	MeshconfConnectedToAs            = 31
	__MeshconfAttrAfterLast          = 32
	MeshconfAttrMax                  = __MeshconfAttrAfterLast - 1
)

// nl80211MeshSetupParams as declared in nl80211/nl80211.h:4446
type nl80211MeshSetupParams int32

// nl80211MeshSetupParams enumeration from nl80211/nl80211.h:4446
const (
	__MeshSetupInvalid           = iota
	MeshSetupEnableVendorPathSel = 1
	MeshSetupEnableVendorMetric  = 2
	MeshSetupIe                  = 3
	MeshSetupUserspaceAuth       = 4
	MeshSetupUserspaceAmpe       = 5
	MeshSetupEnableVendorSync    = 6
	MeshSetupUserspaceMpm        = 7
	MeshSetupAuthProtocol        = 8
	__MeshSetupAttrAfterLast     = 9
	MeshSetupAttrMax             = __MeshSetupAttrAfterLast - 1
)

// nl80211TxqAttr as declared in nl80211/nl80211.h:4476
type nl80211TxqAttr int32

// nl80211TxqAttr enumeration from nl80211/nl80211.h:4476
const (
	__TxqAttrInvalid   = iota
	TxqAttrAc          = 1
	TxqAttrTxop        = 2
	TxqAttrCwmin       = 3
	TxqAttrCwmax       = 4
	TxqAttrAifs        = 5
	__TxqAttrAfterLast = 6
	TxqAttrMax         = __TxqAttrAfterLast - 1
)

// nl80211Ac as declared in nl80211/nl80211.h:4489
type nl80211Ac int32

// nl80211Ac enumeration from nl80211/nl80211.h:4489
const (
	AcVo   = iota
	AcVi   = 1
	AcBe   = 2
	AcBk   = 3
	NumAcs = 4
)

// nl80211ChannelType as declared in nl80211/nl80211.h:4513
type nl80211ChannelType int32

// nl80211ChannelType enumeration from nl80211/nl80211.h:4513
const (
	ChanNoHt      = iota
	ChanHt20      = 1
	ChanHt40minus = 2
	ChanHt40plus  = 3
)

// nl80211KeyMode as declared in nl80211/nl80211.h:4535
type nl80211KeyMode int32

// nl80211KeyMode enumeration from nl80211/nl80211.h:4535
const (
	KeyRxTx  = iota
	KeyNoTx  = 1
	KeySetTx = 2
)

// nl80211ChanWidth as declared in nl80211/nl80211.h:4565
type nl80211ChanWidth int32

// nl80211ChanWidth enumeration from nl80211/nl80211.h:4565
const (
	ChanWidth20Noht = iota
	ChanWidth20     = 1
	ChanWidth40     = 2
	ChanWidth80     = 3
	ChanWidth80p80  = 4
	ChanWidth160    = 5
	ChanWidth5      = 6
	ChanWidth10     = 7
	ChanWidth1      = 8
	ChanWidth2      = 9
	ChanWidth4      = 10
	ChanWidth8      = 11
	ChanWidth16     = 12
)

// nl80211BssScanWidth as declared in nl80211/nl80211.h:4592
type nl80211BssScanWidth int32

// nl80211BssScanWidth enumeration from nl80211/nl80211.h:4592
const (
	BssChanWidth20 = iota
	BssChanWidth10 = 1
	BssChanWidth5  = 2
	BssChanWidth1  = 3
	BssChanWidth2  = 4
)

// nl80211Bss as declared in nl80211/nl80211.h:4653
type nl80211Bss int32

// nl80211Bss enumeration from nl80211/nl80211.h:4653
const (
	__BssInvalid           = iota
	BssBssid               = 1
	BssFrequency           = 2
	BssTsf                 = 3
	BssBeaconInterval      = 4
	BssCapability          = 5
	BssInformationElements = 6
	BssSignalMbm           = 7
	BssSignalUnspec        = 8
	BssStatus              = 9
	BssSeenMsAgo           = 10
	BssBeaconIes           = 11
	BssChanWidth           = 12
	BssBeaconTsf           = 13
	BssPrespData           = 14
	BssLastSeenBoottime    = 15
	BssPad                 = 16
	BssParentTsf           = 17
	BssParentBssid         = 18
	BssChainSignal         = 19
	BssFrequencyOffset     = 20
	__BssAfterLast         = 21
	BssMax                 = __BssAfterLast - 1
)

// nl80211BssStatus as declared in nl80211/nl80211.h:4693
type nl80211BssStatus int32

// nl80211BssStatus enumeration from nl80211/nl80211.h:4693
const (
	BssStatusAuthenticated = iota
	BssStatusAssociated    = 1
	BssStatusIbssJoined    = 2
)

// nl80211AuthType as declared in nl80211/nl80211.h:4716
type nl80211AuthType int32

// nl80211AuthType enumeration from nl80211/nl80211.h:4716
const (
	AuthtypeOpenSystem = iota
	AuthtypeSharedKey  = 1
	AuthtypeFt         = 2
	AuthtypeNetworkEap = 3
	AuthtypeSae        = 4
	AuthtypeFilsSk     = 5
	AuthtypeFilsSkPfs  = 6
	AuthtypeFilsPk     = 7
	__AuthtypeNum      = 8
	AuthtypeMax        = __AuthtypeNum - 1
	AuthtypeAutomatic  = 8
)

// nl80211KeyType as declared in nl80211/nl80211.h:4739
type nl80211KeyType int32

// nl80211KeyType enumeration from nl80211/nl80211.h:4739
const (
	KeytypeGroup    = iota
	KeytypePairwise = 1
	KeytypePeerkey  = 2
	Num_Keytypes    = 3
)

// nl80211Mfp as declared in nl80211/nl80211.h:4753
type nl80211Mfp int32

// nl80211Mfp enumeration from nl80211/nl80211.h:4753
const (
	MfpNo       = iota
	MfpRequired = 1
	MfpOptional = 2
)

// nl80211WpaVersions as declared in nl80211/nl80211.h:4759
type nl80211WpaVersions int32

// nl80211WpaVersions enumeration from nl80211/nl80211.h:4759
const (
	WpaVersion1 = 1 << 0
	WpaVersion2 = 1 << 1
	WpaVersion3 = 1 << 2
)

// nl80211KeyDefaultTypes as declared in nl80211/nl80211.h:4774
type nl80211KeyDefaultTypes int32

// nl80211KeyDefaultTypes enumeration from nl80211/nl80211.h:4774
const (
	__KeyDefaultTypeInvalid = iota
	KeyDefaultTypeUnicast   = 1
	KeyDefaultTypeMulticast = 2
	Num_KeyDefaultTypes     = 3
)

// nl80211KeyAttributes as declared in nl80211/nl80211.h:4808
type nl80211KeyAttributes int32

// nl80211KeyAttributes enumeration from nl80211/nl80211.h:4808
const (
	__KeyInvalid     = iota
	KeyData          = 1
	KeyIdx           = 2
	KeyCipher        = 3
	KeySeq           = 4
	KeyDefault       = 5
	KeyDefaultMgmt   = 6
	KeyType          = 7
	KeyDefaultTypes  = 8
	KeyMode          = 9
	KeyDefaultBeacon = 10
	__KeyAfterLast   = 11
	KeyMax           = __KeyAfterLast - 1
)

// nl80211TxRateAttributes as declared in nl80211/nl80211.h:4845
type nl80211TxRateAttributes int32

// nl80211TxRateAttributes enumeration from nl80211/nl80211.h:4845
const (
	__TxrateInvalid   = iota
	TxrateLegacy      = 1
	TxrateHt          = 2
	TxrateVht         = 3
	TxrateGi          = 4
	TxrateHe          = 5
	TxrateHeGi        = 6
	TxrateHeLtf       = 7
	__TxrateAfterLast = 8
	TxrateMax         = __TxrateAfterLast - 1
)

// nl80211TxrateGi as declared in nl80211/nl80211.h:4880
type nl80211TxrateGi int32

// nl80211TxrateGi enumeration from nl80211/nl80211.h:4880
const (
	TxrateDefaultGi = iota
	TxrateForceSgi  = 1
	TxrateForceLgi  = 2
)

// nl80211Band as declared in nl80211/nl80211.h:4896
type nl80211Band int32

// nl80211Band enumeration from nl80211/nl80211.h:4896
const (
	Band2ghz  = iota
	Band5ghz  = 1
	Band60ghz = 2
	Band6ghz  = 3
	BandS1ghz = 4
	Num_Bands = 5
)

// nl80211PsState as declared in nl80211/nl80211.h:4911
type nl80211PsState int32

// nl80211PsState enumeration from nl80211/nl80211.h:4911
const (
	PsDisabled = iota
	PsEnabled  = 1
)

// nl80211AttrCqm as declared in nl80211/nl80211.h:4949
type nl80211AttrCqm int32

// nl80211AttrCqm enumeration from nl80211/nl80211.h:4949
const (
	__AttrCqmInvalid          = iota
	AttrCqmRssiThold          = 1
	AttrCqmRssiHyst           = 2
	AttrCqmRssiThresholdEvent = 3
	AttrCqmPktLossEvent       = 4
	AttrCqmTxeRate            = 5
	AttrCqmTxePkts            = 6
	AttrCqmTxeIntvl           = 7
	AttrCqmBeaconLossEvent    = 8
	AttrCqmRssiLevel          = 9
	__AttrCqmAfterLast        = 10
	AttrCqmMax                = __AttrCqmAfterLast - 1
)

// nl80211CqmRssiThresholdEvent as declared in nl80211/nl80211.h:4974
type nl80211CqmRssiThresholdEvent int32

// nl80211CqmRssiThresholdEvent enumeration from nl80211/nl80211.h:4974
const (
	CqmRssiThresholdEventLow  = iota
	CqmRssiThresholdEventHigh = 1
	CqmRssiBeaconLossEvent    = 2
)

// nl80211TxPowerSetting as declared in nl80211/nl80211.h:4987
type nl80211TxPowerSetting int32

// nl80211TxPowerSetting enumeration from nl80211/nl80211.h:4987
const (
	TxPowerAutomatic = iota
	TxPowerLimited   = 1
	TxPowerFixed     = 2
)

// nl80211TidConfig as declared in nl80211/nl80211.h:4998
type nl80211TidConfig int32

// nl80211TidConfig enumeration from nl80211/nl80211.h:4998
const (
	TidConfigEnable  = iota
	TidConfigDisable = 1
)

// nl80211TxRateSetting as declared in nl80211/nl80211.h:5008
type nl80211TxRateSetting int32

// nl80211TxRateSetting enumeration from nl80211/nl80211.h:5008
const (
	TxRateAutomatic = iota
	TxRateLimited   = 1
	TxRateFixed     = 2
)

// nl80211TidConfigAttr as declared in nl80211/nl80211.h:5058
type nl80211TidConfigAttr int32

// nl80211TidConfigAttr enumeration from nl80211/nl80211.h:5058
const (
	__TidConfigAttrInvalid   = iota
	TidConfigAttrPad         = 1
	TidConfigAttrVifSupp     = 2
	TidConfigAttrPeerSupp    = 3
	TidConfigAttrOverride    = 4
	TidConfigAttrTids        = 5
	TidConfigAttrNoack       = 6
	TidConfigAttrRetryShort  = 7
	TidConfigAttrRetryLong   = 8
	TidConfigAttrAmpduCtrl   = 9
	TidConfigAttrRtsctsCtrl  = 10
	TidConfigAttrAmsduCtrl   = 11
	TidConfigAttrTxRateType  = 12
	TidConfigAttrTxRate      = 13
	__TidConfigAttrAfterLast = 14
	TidConfigAttrMax         = __TidConfigAttrAfterLast - 1
)

// nl80211PacketPatternAttr as declared in nl80211/nl80211.h:5100
type nl80211PacketPatternAttr int32

// nl80211PacketPatternAttr enumeration from nl80211/nl80211.h:5100
const (
	__PktpatInvalid = iota
	PktpatMask      = 1
	PktpatPattern   = 2
	PktpatOffset    = 3
	Num_Pktpat      = 4
	Max_Pktpat      = Num_Pktpat - 1
)

// nl80211WowlanTriggers as declared in nl80211/nl80211.h:5228
type nl80211WowlanTriggers int32

// nl80211WowlanTriggers enumeration from nl80211/nl80211.h:5228
const (
	__WowlanTrigInvalid             = iota
	WowlanTrigAny                   = 1
	WowlanTrigDisconnect            = 2
	WowlanTrigMagicPkt              = 3
	WowlanTrigPktPattern            = 4
	WowlanTrigGtkRekeySupported     = 5
	WowlanTrigGtkRekeyFailure       = 6
	WowlanTrigEapIdentRequest       = 7
	WowlanTrig4wayHandshake         = 8
	WowlanTrigRfkillRelease         = 9
	WowlanTrigWakeupPkt80211        = 10
	WowlanTrigWakeupPkt80211Len     = 11
	WowlanTrigWakeupPkt8023         = 12
	WowlanTrigWakeupPkt8023Len      = 13
	WowlanTrigTcpConnection         = 14
	WowlanTrigWakeupTcpMatch        = 15
	WowlanTrigWakeupTcpConnlost     = 16
	WowlanTrigWakeupTcpNomoretokens = 17
	WowlanTrigNetDetect             = 18
	WowlanTrigNetDetectResults      = 19
	Num_WowlanTrig                  = 20
	Max_WowlanTrig                  = Num_WowlanTrig - 1
)

// nl80211WowlanTcpAttrs as declared in nl80211/nl80211.h:5346
type nl80211WowlanTcpAttrs int32

// nl80211WowlanTcpAttrs enumeration from nl80211/nl80211.h:5346
const (
	__WowlanTcpInvalid        = iota
	WowlanTcpSrcIpv4          = 1
	WowlanTcpDstIpv4          = 2
	WowlanTcpDstMac           = 3
	WowlanTcpSrcPort          = 4
	WowlanTcpDstPort          = 5
	WowlanTcpDataPayload      = 6
	WowlanTcpDataPayloadSeq   = 7
	WowlanTcpDataPayloadToken = 8
	WowlanTcpDataInterval     = 9
	WowlanTcpWakePayload      = 10
	WowlanTcpWakeMask         = 11
	Num_WowlanTcp             = 12
	Max_WowlanTcp             = Num_WowlanTcp - 1
)

// nl80211AttrCoalesceRule as declared in nl80211/nl80211.h:5391
type nl80211AttrCoalesceRule int32

// nl80211AttrCoalesceRule enumeration from nl80211/nl80211.h:5391
const (
	__CoalesceRuleInvalid      = iota
	AttrCoalesceRuleDelay      = 1
	AttrCoalesceRuleCondition  = 2
	AttrCoalesceRulePktPattern = 3
	Num_AttrCoalesceRule       = 4
	AttrCoalesceRuleMax        = Num_AttrCoalesceRule - 1
)

// nl80211CoalesceCondition as declared in nl80211/nl80211.h:5409
type nl80211CoalesceCondition int32

// nl80211CoalesceCondition enumeration from nl80211/nl80211.h:5409
const (
	CoalesceConditionMatch   = iota
	CoalesceConditionNoMatch = 1
)

// nl80211IfaceLimitAttrs as declared in nl80211/nl80211.h:5424
type nl80211IfaceLimitAttrs int32

// nl80211IfaceLimitAttrs enumeration from nl80211/nl80211.h:5424
const (
	IfaceLimitUnspec = iota
	IfaceLimitMax    = 1
	IfaceLimitTypes  = 2
	Num_IfaceLimit   = 3
	Max_IfaceLimit   = Num_IfaceLimit - 1
)

// nl80211IfCombinationAttrs as declared in nl80211/nl80211.h:5483
type nl80211IfCombinationAttrs int32

// nl80211IfCombinationAttrs enumeration from nl80211/nl80211.h:5483
const (
	IfaceCombUnspec             = iota
	IfaceCombLimits             = 1
	IfaceCombMaxnum             = 2
	IfaceCombStaApBiMatch       = 3
	IfaceCombNumChannels        = 4
	IfaceCombRadarDetectWidths  = 5
	IfaceCombRadarDetectRegions = 6
	IfaceCombBiMinGcd           = 7
	Num_IfaceComb               = 8
	Max_IfaceComb               = Num_IfaceComb - 1
)

// nl80211PlinkState as declared in nl80211/nl80211.h:5517
type nl80211PlinkState int32

// nl80211PlinkState enumeration from nl80211/nl80211.h:5517
const (
	PlinkListen     = iota
	PlinkOpnSnt     = 1
	PlinkOpnRcvd    = 2
	PlinkCnfRcvd    = 3
	PlinkEstab      = 4
	PlinkHolding    = 5
	PlinkBlocked    = 6
	Num_PlinkStates = 7
	Max_PlinkStates = Num_PlinkStates - 1
)

// plinkActions as declared in nl80211/nl80211.h:5539
type plinkActions int32

// plinkActions enumeration from nl80211/nl80211.h:5539
const (
	PlinkActionNoAction = iota
	PlinkActionOpen     = 1
	PlinkActionBlock    = 2
	Num_PlinkActions    = 3
)

// nl80211RekeyData as declared in nl80211/nl80211.h:5564
type nl80211RekeyData int32

// nl80211RekeyData enumeration from nl80211/nl80211.h:5564
const (
	__RekeyDataInvalid = iota
	RekeyDataKek       = 1
	RekeyDataKck       = 2
	RekeyDataReplayCtr = 3
	RekeyDataAkm       = 4
	Num_RekeyData      = 5
	Max_RekeyData      = Num_RekeyData - 1
)

// nl80211HiddenSsid as declared in nl80211/nl80211.h:5585
type nl80211HiddenSsid int32

// nl80211HiddenSsid enumeration from nl80211/nl80211.h:5585
const (
	HiddenSsidNotInUse     = iota
	HiddenSsidZeroLen      = 1
	HiddenSsidZeroContents = 2
)

// nl80211StaWmeAttr as declared in nl80211/nl80211.h:5601
type nl80211StaWmeAttr int32

// nl80211StaWmeAttr enumeration from nl80211/nl80211.h:5601
const (
	__StaWmeInvalid   = iota
	StaWmeUapsdQueues = 1
	StaWmeMaxSp       = 2
	__StaWmeAfterLast = 3
	StaWmeMax         = __StaWmeAfterLast - 1
)

// nl80211PmksaCandidateAttr as declared in nl80211/nl80211.h:5623
type nl80211PmksaCandidateAttr int32

// nl80211PmksaCandidateAttr enumeration from nl80211/nl80211.h:5623
const (
	__PmksaCandidateInvalid = iota
	PmksaCandidateIndex     = 1
	PmksaCandidateBssid     = 2
	PmksaCandidatePreauth   = 3
	Num_PmksaCandidate      = 4
	Max_PmksaCandidate      = Num_PmksaCandidate - 1
)

// nl80211TdlsOperation as declared in nl80211/nl80211.h:5642
type nl80211TdlsOperation int32

// nl80211TdlsOperation enumeration from nl80211/nl80211.h:5642
const (
	TdlsDiscoveryReq = iota
	TdlsSetup        = 1
	TdlsTeardown     = 2
	TdlsEnableLink   = 3
	TdlsDisableLink  = 4
)

// nl80211FeatureFlags as declared in nl80211/nl80211.h:5751
type nl80211FeatureFlags int32

// nl80211FeatureFlags enumeration from nl80211/nl80211.h:5751
const (
	FeatureSkTxStatus             = 1 << 0
	FeatureHtIbss                 = 1 << 1
	FeatureInactivityTimer        = 1 << 2
	FeatureCellBaseRegHints       = 1 << 3
	FeatureP2pDeviceNeedsChannel  = 1 << 4
	FeatureSae                    = 1 << 5
	FeatureLowPriorityScan        = 1 << 6
	FeatureScanFlush              = 1 << 7
	FeatureApScan                 = 1 << 8
	FeatureVifTxpower             = 1 << 9
	FeatureNeedObssScan           = 1 << 10
	FeatureP2pGoCtwin             = 1 << 11
	FeatureP2pGoOppps             = 1 << 12
	FeatureAdvertiseChanLimits    = 1 << 14
	FeatureFullApClientState      = 1 << 15
	FeatureUserspaceMpm           = 1 << 16
	FeatureActiveMonitor          = 1 << 17
	FeatureApModeChanWidthChange  = 1 << 18
	FeatureDsParamSetIeInProbes   = 1 << 19
	FeatureWfaTpcIeInProbes       = 1 << 20
	FeatureQuiet                  = 1 << 21
	FeatureTxPowerInsertion       = 1 << 22
	FeatureAcktoEstimation        = 1 << 23
	FeatureStaticSmps             = 1 << 24
	FeatureDynamicSmps            = 1 << 25
	FeatureSupportsWmmAdmission   = 1 << 26
	FeatureMacOnCreate            = 1 << 27
	FeatureTdlsChannelSwitch      = 1 << 28
	FeatureScanRandomMacAddr      = 1 << 29
	FeatureSchedScanRandomMacAddr = 1 << 30
	FeatureNdRandomMacAddr        = uint32(1) << 31
)

// nl80211ExtFeatureIndex as declared in nl80211/nl80211.h:5959
type nl80211ExtFeatureIndex int32

// nl80211ExtFeatureIndex enumeration from nl80211/nl80211.h:5959
const (
	ExtFeatureVhtIbss                        = iota
	ExtFeatureRrm                            = 1
	ExtFeatureMuMimoAirSniffer               = 2
	ExtFeatureScanStartTime                  = 3
	ExtFeatureBssParentTsf                   = 4
	ExtFeatureSetScanDwell                   = 5
	ExtFeatureBeaconRateLegacy               = 6
	ExtFeatureBeaconRateHt                   = 7
	ExtFeatureBeaconRateVht                  = 8
	ExtFeatureFilsSta                        = 9
	ExtFeatureMgmtTxRandomTa                 = 10
	ExtFeatureMgmtTxRandomTaConnected        = 11
	ExtFeatureSchedScanRelativeRssi          = 12
	ExtFeatureCqmRssiList                    = 13
	ExtFeatureFilsSkOffload                  = 14
	ExtFeature4wayHandshakeStaPsk            = 15
	ExtFeature4wayHandshakeSta1x             = 16
	ExtFeatureFilsMaxChannelTime             = 17
	ExtFeatureAcceptBcastProbeResp           = 18
	ExtFeatureOceProbeReqHighTxRate          = 19
	ExtFeatureOceProbeReqDeferralSuppression = 20
	ExtFeatureMfpOptional                    = 21
	ExtFeatureLowSpanScan                    = 22
	ExtFeatureLowPowerScan                   = 23
	ExtFeatureHighAccuracyScan               = 24
	ExtFeatureDfsOffload                     = 25
	ExtFeatureControlPortOverNl80211         = 26
	ExtFeatureAckSignalSupport               = 27
	ExtFeatureDataAckSignalSupport           = ExtFeatureAckSignalSupport
	ExtFeatureTxqs                           = 28
	ExtFeatureScanRandomSn                   = 29
	ExtFeatureScanMinPreqContent             = 30
	ExtFeatureCanReplacePtk0                 = 31
	ExtFeatureEnableFtmResponder             = 32
	ExtFeatureAirtimeFairness                = 33
	ExtFeatureApPmksaCaching                 = 34
	ExtFeatureSchedScanBandSpecificRssiThold = 35
	ExtFeatureExtKeyId                       = 36
	ExtFeatureStaTxPwr                       = 37
	ExtFeatureSaeOffload                     = 38
	ExtFeatureVlanOffload                    = 39
	ExtFeatureAql                            = 40
	ExtFeatureBeaconProtection               = 41
	ExtFeatureControlPortNoPreauth           = 42
	ExtFeatureProtectedTwt                   = 43
	ExtFeatureDelIbssSta                     = 44
	ExtFeatureMulticastRegistrations         = 45
	ExtFeatureBeaconProtectionClient         = 46
	ExtFeatureScanFreqKhz                    = 47
	ExtFeatureControlPortOver_TxStatus       = 48
	ExtFeatureOperatingChannelValidation     = 49
	ExtFeature4wayHandshakeApPsk             = 50
	ExtFeatureSaeOffloadAp                   = 51
	ExtFeatureFilsDiscovery                  = 52
	ExtFeatureUnsolBcastProbeResp            = 53
	ExtFeatureBeaconRateHe                   = 54
	ExtFeatureSecureLtf                      = 55
	ExtFeatureSecureRtt                      = 56
	ExtFeatureProtRangeNegoAndMeasure        = 57
	Num_ExtFeatures                          = 58
	Max_ExtFeatures                          = Num_ExtFeatures - 1
)

// nl80211ProbeRespOffloadSupportAttr as declared in nl80211/nl80211.h:6040
type nl80211ProbeRespOffloadSupportAttr int32

// nl80211ProbeRespOffloadSupportAttr enumeration from nl80211/nl80211.h:6040
const (
	ProbeRespOffloadSupportWps    = 1 << 0
	ProbeRespOffloadSupportWps2   = 1 << 1
	ProbeRespOffloadSupportP2p    = 1 << 2
	ProbeRespOffloadSupport80211u = 1 << 3
)

// nl80211ConnectFailedReason as declared in nl80211/nl80211.h:6053
type nl80211ConnectFailedReason int32

// nl80211ConnectFailedReason enumeration from nl80211/nl80211.h:6053
const (
	ConnFailMaxClients    = iota
	ConnFailBlockedClient = 1
)

// nl80211TimeoutReason as declared in nl80211/nl80211.h:6066
type nl80211TimeoutReason int32

// nl80211TimeoutReason enumeration from nl80211/nl80211.h:6066
const (
	TimeoutUnspecified = iota
	TimeoutScan        = 1
	TimeoutAuth        = 2
	TimeoutAssoc       = 3
)

// nl80211ScanFlags as declared in nl80211/nl80211.h:6137
type nl80211ScanFlags int32

// nl80211ScanFlags enumeration from nl80211/nl80211.h:6137
const (
	ScanFlagLowPriority                    = 1 << 0
	ScanFlagFlush                          = 1 << 1
	ScanFlagAp                             = 1 << 2
	ScanFlagRandomAddr                     = 1 << 3
	ScanFlagFilsMaxChannelTime             = 1 << 4
	ScanFlagAcceptBcastProbeResp           = 1 << 5
	ScanFlagOceProbeReqHighTxRate          = 1 << 6
	ScanFlagOceProbeReqDeferralSuppression = 1 << 7
	ScanFlagLowSpan                        = 1 << 8
	ScanFlagLowPower                       = 1 << 9
	ScanFlagHighAccuracy                   = 1 << 10
	ScanFlagRandomSn                       = 1 << 11
	ScanFlagMinPreqContent                 = 1 << 12
	ScanFlagFreqKhz                        = 1 << 13
	ScanFlagColocated6ghz                  = 1 << 14
)

// nl80211AclPolicy as declared in nl80211/nl80211.h:6168
type nl80211AclPolicy int32

// nl80211AclPolicy enumeration from nl80211/nl80211.h:6168
const (
	AclPolicyAcceptUnlessListed = iota
	AclPolicyDenyUnlessListed   = 1
)

// nl80211SmpsMode as declared in nl80211/nl80211.h:6183
type nl80211SmpsMode int32

// nl80211SmpsMode enumeration from nl80211/nl80211.h:6183
const (
	SmpsOff         = iota
	SmpsStatic      = 1
	SmpsDynamic     = 2
	__SmpsAfterLast = 3
	SmpsMax         = __SmpsAfterLast - 1
)

// nl80211RadarEvent as declared in nl80211/nl80211.h:6213
type nl80211RadarEvent int32

// nl80211RadarEvent enumeration from nl80211/nl80211.h:6213
const (
	RadarDetected      = iota
	RadarCacFinished   = 1
	RadarCacAborted    = 2
	RadarNopFinished   = 3
	RadarPreCacExpired = 4
	RadarCacStarted    = 5
)

// nl80211DfsState as declared in nl80211/nl80211.h:6233
type nl80211DfsState int32

// nl80211DfsState enumeration from nl80211/nl80211.h:6233
const (
	DfsUsable      = iota
	DfsUnavailable = 1
	DfsAvailable   = 2
)

// nl80211ProtocolFeatures as declared in nl80211/nl80211.h:6247
type nl80211ProtocolFeatures int32

// nl80211ProtocolFeatures enumeration from nl80211/nl80211.h:6247
const (
	ProtocolFeatureSplitWiphyDump = 1 << 0
)

// nl80211CritProtoId as declared in nl80211/nl80211.h:6260
type nl80211CritProtoId int32

// nl80211CritProtoId enumeration from nl80211/nl80211.h:6260
const (
	CritProtoUnspec = iota
	CritProtoDhcp   = 1
	CritProtoEapol  = 2
	CritProtoApipa  = 3
	Num_CritProto   = 4
)

// nl80211RxmgmtFlags as declared in nl80211/nl80211.h:6283
type nl80211RxmgmtFlags int32

// nl80211RxmgmtFlags enumeration from nl80211/nl80211.h:6283
const (
	RxmgmtFlagAnswered     = 1 << 0
	RxmgmtFlagExternalAuth = 1 << 1
)

// nl80211TdlsPeerCapability as declared in nl80211/nl80211.h:6319
type nl80211TdlsPeerCapability int32

// nl80211TdlsPeerCapability enumeration from nl80211/nl80211.h:6319
const (
	TdlsPeerHt  = 1 << 0
	TdlsPeerVht = 1 << 1
	TdlsPeerWmm = 1 << 2
	TdlsPeerHe  = 1 << 3
)

// nl80211SchedScanPlan as declared in nl80211/nl80211.h:6339
type nl80211SchedScanPlan int32

// nl80211SchedScanPlan enumeration from nl80211/nl80211.h:6339
const (
	__SchedScanPlanInvalid   = iota
	SchedScanPlanInterval    = 1
	SchedScanPlanIterations  = 2
	__SchedScanPlanAfterLast = 3
	SchedScanPlanMax         = __SchedScanPlanAfterLast - 1
)

// nl80211BssSelectAttr as declared in nl80211/nl80211.h:6384
type nl80211BssSelectAttr int32

// nl80211BssSelectAttr enumeration from nl80211/nl80211.h:6384
const (
	__BssSelectAttrInvalid   = iota
	BssSelectAttrRssi        = 1
	BssSelectAttrBandPref    = 2
	BssSelectAttrRssiAdjust  = 3
	__BssSelectAttrAfterLast = 4
	BssSelectAttrMax         = __BssSelectAttrAfterLast - 1
)

// nl80211NanFunctionType as declared in nl80211/nl80211.h:6404
type nl80211NanFunctionType int32

// nl80211NanFunctionType enumeration from nl80211/nl80211.h:6404
const (
	NanFuncPublish         = iota
	NanFuncSubscribe       = 1
	NanFuncFollowUp        = 2
	__NanFuncTypeAfterLast = 3
	NanFuncMaxType         = __NanFuncTypeAfterLast - 1
)

// nl80211NanPublishType as declared in nl80211/nl80211.h:6422
type nl80211NanPublishType int32

// nl80211NanPublishType enumeration from nl80211/nl80211.h:6422
const (
	NanSolicitedPublish   = 1 << 0
	NanUnsolicitedPublish = 1 << 1
)

// nl80211NanFuncTermReason as declared in nl80211/nl80211.h:6436
type nl80211NanFuncTermReason int32

// nl80211NanFuncTermReason enumeration from nl80211/nl80211.h:6436
const (
	NanFuncTermReasonUserRequest = iota
	NanFuncTermReasonTtlExpired  = 1
	NanFuncTermReasonError       = 2
)

// nl80211NanFuncAttributes as declared in nl80211/nl80211.h:6488
type nl80211NanFuncAttributes int32

// nl80211NanFuncAttributes enumeration from nl80211/nl80211.h:6488
const (
	__NanFuncInvalid       = iota
	NanFuncType            = 1
	NanFuncServiceId       = 2
	NanFuncPublishType     = 3
	NanFuncPublishBcast    = 4
	NanFuncSubscribeActive = 5
	NanFuncFollowUpId      = 6
	NanFuncFollowUpReqId   = 7
	NanFuncFollowUpDest    = 8
	NanFuncCloseRange      = 9
	NanFuncTtl             = 10
	NanFuncServiceInfo     = 11
	NanFuncSrf             = 12
	NanFuncRxMatchFilter   = 13
	NanFuncTxMatchFilter   = 14
	NanFuncInstanceId      = 15
	NanFuncTermReason      = 16
	Num_NanFuncAttr        = 17
	NanFuncAttrMax         = Num_NanFuncAttr - 1
)

// nl80211NanSrfAttributes as declared in nl80211/nl80211.h:6527
type nl80211NanSrfAttributes int32

// nl80211NanSrfAttributes enumeration from nl80211/nl80211.h:6527
const (
	__NanSrfInvalid = iota
	NanSrfInclude   = 1
	NanSrfBf        = 2
	NanSrfBfIdx     = 3
	NanSrfMacAddrs  = 4
	Num_NanSrfAttr  = 5
	NanSrfAttrMax   = Num_NanSrfAttr - 1
)

// nl80211NanMatchAttributes as declared in nl80211/nl80211.h:6552
type nl80211NanMatchAttributes int32

// nl80211NanMatchAttributes enumeration from nl80211/nl80211.h:6552
const (
	__NanMatchInvalid = iota
	NanMatchFuncLocal = 1
	NanMatchFuncPeer  = 2
	Num_NanMatchAttr  = 3
	NanMatchAttrMax   = Num_NanMatchAttr - 1
)

// nl80211ExternalAuthAction as declared in nl80211/nl80211.h:6568
type nl80211ExternalAuthAction int32

// nl80211ExternalAuthAction enumeration from nl80211/nl80211.h:6568
const (
	ExternalAuthStart = iota
	ExternalAuthAbort = 1
)

// nl80211FtmResponderAttributes as declared in nl80211/nl80211.h:6587
type nl80211FtmResponderAttributes int32

// nl80211FtmResponderAttributes enumeration from nl80211/nl80211.h:6587
const (
	__FtmRespAttrInvalid = iota
	FtmRespAttrEnabled   = 1
	FtmRespAttrLci       = 2
	FtmRespAttrCivicloc  = 3
	__FtmRespAttrLast    = 4
	FtmRespAttrMax       = __FtmRespAttrLast - 1
)

// nl80211FtmResponderStats as declared in nl80211/nl80211.h:6627
type nl80211FtmResponderStats int32

// nl80211FtmResponderStats enumeration from nl80211/nl80211.h:6627
const (
	__FtmStatsInvalid              = iota
	FtmStatsSuccessNum             = 1
	FtmStatsPartialNum             = 2
	FtmStatsFailedNum              = 3
	FtmStatsAsapNum                = 4
	FtmStatsNonAsapNum             = 5
	FtmStatsTotalDurationMsec      = 6
	FtmStatsUnknownTriggersNum     = 7
	FtmStatsRescheduleRequestsNum  = 8
	FtmStatsOutOfWindowTriggersNum = 9
	FtmStatsPad                    = 10
	__FtmStatsAfterLast            = 11
	FtmStatsMax                    = __FtmStatsAfterLast - 1
)

// nl80211Preamble as declared in nl80211/nl80211.h:6653
type nl80211Preamble int32

// nl80211Preamble enumeration from nl80211/nl80211.h:6653
const (
	PreambleLegacy = iota
	PreambleHt     = 1
	PreambleVht    = 2
	PreambleDmg    = 3
	PreambleHe     = 4
)

// nl80211PeerMeasurementType as declared in nl80211/nl80211.h:6671
type nl80211PeerMeasurementType int32

// nl80211PeerMeasurementType enumeration from nl80211/nl80211.h:6671
const (
	PmsrTypeInvalid = iota
	PmsrTypeFtm     = 1
	Num_PmsrTypes   = 2
	PmsrTypeMax     = Num_PmsrTypes - 1
)

// nl80211PeerMeasurementStatus as declared in nl80211/nl80211.h:6688
type nl80211PeerMeasurementStatus int32

// nl80211PeerMeasurementStatus enumeration from nl80211/nl80211.h:6688
const (
	PmsrStatusSuccess = iota
	PmsrStatusRefused = 1
	PmsrStatusTimeout = 2
	PmsrStatusFailure = 3
)

// nl80211PeerMeasurementReq as declared in nl80211/nl80211.h:6708
type nl80211PeerMeasurementReq int32

// nl80211PeerMeasurementReq enumeration from nl80211/nl80211.h:6708
const (
	__PmsrReqAttrInvalid = iota
	PmsrReqAttrData      = 1
	PmsrReqAttrGetApTsf  = 2
	Num_PmsrReqAttrs     = 3
	PmsrReqAttrMax       = Num_PmsrReqAttrs - 1
)

// nl80211PeerMeasurementResp as declared in nl80211/nl80211.h:6744
type nl80211PeerMeasurementResp int32

// nl80211PeerMeasurementResp enumeration from nl80211/nl80211.h:6744
const (
	__PmsrRespAttrInvalid = iota
	PmsrRespAttrData      = 1
	PmsrRespAttrStatus    = 2
	PmsrRespAttrHostTime  = 3
	PmsrRespAttrApTsf     = 4
	PmsrRespAttrFinal     = 5
	PmsrRespAttrPad       = 6
	Num_PmsrRespAttrs     = 7
	PmsrRespAttrMax       = Num_PmsrRespAttrs - 1
)

// nl80211PeerMeasurementPeerAttrs as declared in nl80211/nl80211.h:6776
type nl80211PeerMeasurementPeerAttrs int32

// nl80211PeerMeasurementPeerAttrs enumeration from nl80211/nl80211.h:6776
const (
	__PmsrPeerAttrInvalid = iota
	PmsrPeerAttrAddr      = 1
	PmsrPeerAttrChan      = 2
	PmsrPeerAttrReq       = 3
	PmsrPeerAttrResp      = 4
	Num_PmsrPeerAttrs     = 5
	PmsrPeerAttrMax       = Num_PmsrPeerAttrs - 1
)

// nl80211PeerMeasurementAttrs as declared in nl80211/nl80211.h:6813
type nl80211PeerMeasurementAttrs int32

// nl80211PeerMeasurementAttrs enumeration from nl80211/nl80211.h:6813
const (
	__PmsrAttrInvalid        = iota
	PmsrAttrMaxPeers         = 1
	PmsrAttrReportApTsf      = 2
	PmsrAttrRandomizeMacAddr = 3
	PmsrAttrTypeCapa         = 4
	PmsrAttrPeers            = 5
	Num_PmsrAttr             = 6
	PmsrAttrMax              = Num_PmsrAttr - 1
)

// nl80211PeerMeasurementFtmCapa as declared in nl80211/nl80211.h:6859
type nl80211PeerMeasurementFtmCapa int32

// nl80211PeerMeasurementFtmCapa enumeration from nl80211/nl80211.h:6859
const (
	__PmsrFtmCapaAttrInvalid         = iota
	PmsrFtmCapaAttrAsap              = 1
	PmsrFtmCapaAttrNonAsap           = 2
	PmsrFtmCapaAttrReqLci            = 3
	PmsrFtmCapaAttrReqCivicloc       = 4
	PmsrFtmCapaAttrPreambles         = 5
	PmsrFtmCapaAttrBandwidths        = 6
	PmsrFtmCapaAttrMaxBurstsExponent = 7
	PmsrFtmCapaAttrMaxFtmsPerBurst   = 8
	PmsrFtmCapaAttrTriggerBased      = 9
	PmsrFtmCapaAttrNonTriggerBased   = 10
	Num_PmsrFtmCapaAttr              = 11
	PmsrFtmCapaAttrMax               = Num_PmsrFtmCapaAttr - 1
)

// nl80211PeerMeasurementFtmReq as declared in nl80211/nl80211.h:6925
type nl80211PeerMeasurementFtmReq int32

// nl80211PeerMeasurementFtmReq enumeration from nl80211/nl80211.h:6925
const (
	__PmsrFtmReqAttrInvalid       = iota
	PmsrFtmReqAttrAsap            = 1
	PmsrFtmReqAttrPreamble        = 2
	PmsrFtmReqAttrNumBurstsExp    = 3
	PmsrFtmReqAttrBurstPeriod     = 4
	PmsrFtmReqAttrBurstDuration   = 5
	PmsrFtmReqAttrFtmsPerBurst    = 6
	PmsrFtmReqAttrNumFtmrRetries  = 7
	PmsrFtmReqAttrRequestLci      = 8
	PmsrFtmReqAttrRequestCivicloc = 9
	PmsrFtmReqAttrTriggerBased    = 10
	PmsrFtmReqAttrNonTriggerBased = 11
	PmsrFtmReqAttrLmrFeedback     = 12
	PmsrFtmReqAttrBssColor        = 13
	Num_PmsrFtmReqAttr            = 14
	PmsrFtmReqAttrMax             = Num_PmsrFtmReqAttr - 1
)

// nl80211PeerMeasurementFtmFailureReasons as declared in nl80211/nl80211.h:6963
type nl80211PeerMeasurementFtmFailureReasons int32

// nl80211PeerMeasurementFtmFailureReasons enumeration from nl80211/nl80211.h:6963
const (
	PmsrFtmFailureUnspecified      = iota
	PmsrFtmFailureNoResponse       = 1
	PmsrFtmFailureRejected         = 2
	PmsrFtmFailureWrongChannel     = 3
	PmsrFtmFailurePeerNotCapable   = 4
	PmsrFtmFailureInvalidTimestamp = 5
	PmsrFtmFailurePeerBusy         = 6
	PmsrFtmFailureBadChangedParams = 7
)

// nl80211PeerMeasurementFtmResp as declared in nl80211/nl80211.h:7029
type nl80211PeerMeasurementFtmResp int32

// nl80211PeerMeasurementFtmResp enumeration from nl80211/nl80211.h:7029
const (
	__PmsrFtmRespAttrInvalid        = iota
	PmsrFtmRespAttrFailReason       = 1
	PmsrFtmRespAttrBurstIndex       = 2
	PmsrFtmRespAttrNumFtmrAttempts  = 3
	PmsrFtmRespAttrNumFtmrSuccesses = 4
	PmsrFtmRespAttrBusyRetryTime    = 5
	PmsrFtmRespAttrNumBurstsExp     = 6
	PmsrFtmRespAttrBurstDuration    = 7
	PmsrFtmRespAttrFtmsPerBurst     = 8
	PmsrFtmRespAttrRssiAvg          = 9
	PmsrFtmRespAttrRssiSpread       = 10
	PmsrFtmRespAttrTxRate           = 11
	PmsrFtmRespAttrRxRate           = 12
	PmsrFtmRespAttrRttAvg           = 13
	PmsrFtmRespAttrRttVariance      = 14
	PmsrFtmRespAttrRttSpread        = 15
	PmsrFtmRespAttrDistAvg          = 16
	PmsrFtmRespAttrDistVariance     = 17
	PmsrFtmRespAttrDistSpread       = 18
	PmsrFtmRespAttrLci              = 19
	PmsrFtmRespAttrCivicloc         = 20
	PmsrFtmRespAttrPad              = 21
	Num_PmsrFtmRespAttr             = 22
	PmsrFtmRespAttrMax              = Num_PmsrFtmRespAttr - 1
)

// nl80211ObssPdAttributes as declared in nl80211/nl80211.h:7076
type nl80211ObssPdAttributes int32

// nl80211ObssPdAttributes enumeration from nl80211/nl80211.h:7076
const (
	__HeObssPdAttrInvalid          = iota
	HeObssPdAttrMinOffset          = 1
	HeObssPdAttrMaxOffset          = 2
	HeObssPdAttrNonSrgMaxOffset    = 3
	HeObssPdAttrBssColorBitmap     = 4
	HeObssPdAttrPartialBssidBitmap = 5
	HeObssPdAttrSrCtrl             = 6
	__HeObssPdAttrLast             = 7
	HeObssPdAttrMax                = __HeObssPdAttrLast - 1
)

// nl80211BssColorAttributes as declared in nl80211/nl80211.h:7102
type nl80211BssColorAttributes int32

// nl80211BssColorAttributes enumeration from nl80211/nl80211.h:7102
const (
	__HeBssColorAttrInvalid = iota
	HeBssColorAttrColor     = 1
	HeBssColorAttrDisabled  = 2
	HeBssColorAttrPartial   = 3
	__HeBssColorAttrLast    = 4
	HeBssColorAttrMax       = __HeBssColorAttrLast - 1
)

// nl80211IftypeAkmAttributes as declared in nl80211/nl80211.h:7127
type nl80211IftypeAkmAttributes int32

// nl80211IftypeAkmAttributes enumeration from nl80211/nl80211.h:7127
const (
	__IftypeAkmAttrInvalid = iota
	IftypeAkmAttrIftypes   = 1
	IftypeAkmAttrSuites    = 2
	__IftypeAkmAttrLast    = 3
	IftypeAkmAttrMax       = __IftypeAkmAttrLast - 1
)

// nl80211FilsDiscoveryAttributes as declared in nl80211/nl80211.h:7154
type nl80211FilsDiscoveryAttributes int32

// nl80211FilsDiscoveryAttributes enumeration from nl80211/nl80211.h:7154
const (
	__FilsDiscoveryAttrInvalid = iota
	FilsDiscoveryAttrIntMin    = 1
	FilsDiscoveryAttrIntMax    = 2
	FilsDiscoveryAttrTmpl      = 3
	__FilsDiscoveryAttrLast    = 4
	FilsDiscoveryAttrMax       = __FilsDiscoveryAttrLast - 1
)

// nl80211UnsolBcastProbeRespAttributes as declared in nl80211/nl80211.h:7187
type nl80211UnsolBcastProbeRespAttributes int32

// nl80211UnsolBcastProbeRespAttributes enumeration from nl80211/nl80211.h:7187
const (
	__UnsolBcastProbeRespAttrInvalid = iota
	UnsolBcastProbeRespAttrInt       = 1
	UnsolBcastProbeRespAttrTmpl      = 2
	__UnsolBcastProbeRespAttrLast    = 3
	UnsolBcastProbeRespAttrMax       = __UnsolBcastProbeRespAttrLast - 1
)

// nl80211SaePweMechanism as declared in nl80211/nl80211.h:7211
type nl80211SaePweMechanism int32

// nl80211SaePweMechanism enumeration from nl80211/nl80211.h:7211
const (
	SaePweUnspecified   = iota
	SaePweHuntAndPeck   = 1
	SaePweHashToElement = 2
	SaePweBoth          = 3
)

// nl80211SarType as declared in nl80211/nl80211.h:7224
type nl80211SarType int32

// nl80211SarType enumeration from nl80211/nl80211.h:7224
const (
	SarTypePower = iota
	Num_SarType  = 1
)

// nl80211SarAttrs as declared in nl80211/nl80211.h:7254
type nl80211SarAttrs int32

// nl80211SarAttrs enumeration from nl80211/nl80211.h:7254
const (
	__SarAttrInvalid = iota
	SarAttrType      = 1
	SarAttrSpecs     = 2
	__SarAttrLast    = 3
	SarAttrMax       = __SarAttrLast - 1
)

// nl80211SarSpecsAttrs as declared in nl80211/nl80211.h:7297
type nl80211SarSpecsAttrs int32

// nl80211SarSpecsAttrs enumeration from nl80211/nl80211.h:7297
const (
	__SarAttrSpecsInvalid  = iota
	SarAttrSpecsPower      = 1
	SarAttrSpecsRangeIndex = 2
	SarAttrSpecsStartFreq  = 3
	SarAttrSpecsEndFreq    = 4
	__SarAttrSpecsLast     = 5
	SarAttrSpecsMax        = __SarAttrSpecsLast - 1
)
